/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EmbeddedUserSession } from "./utils/EmbededUserSession";
import { MatchResults, RouterHistory } from "@stencil/router";
import { UserSession } from "@esri/arcgis-rest-auth";
export namespace Components {
    interface AgoIdentity {
        "session": EmbeddedUserSession;
    }
    interface AgoIframe {
        "iframeUrl": string;
        "parentOrigin": string;
        "url": string;
    }
    interface AgoSignin {
        /**
          * ClientID to identify the app launching OAuth
         */
        "clientid": string;
        "displaysignin": boolean;
        "displaysignout": boolean;
        /**
          * url of the ArcGIS Online organization
         */
        "orgurl": string;
        /**
          * Serialized authentication information.
         */
        "session": EmbeddedUserSession;
        "signin": string;
        "signout": string;
    }
    interface AppEmbed {
        "embeds": string[];
        "match": MatchResults;
        "validOrigins": string[];
    }
    interface AppHome {
    }
    interface AppNav {
    }
    interface AppPage {
        "history": RouterHistory;
        "item": any;
        "loading": boolean;
        "match": MatchResults;
        "messages": string[];
        "parentOrigin": string;
        "session": UserSession;
        "targetItemId": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAgoIdentityElement extends Components.AgoIdentity, HTMLStencilElement {
    }
    var HTMLAgoIdentityElement: {
        prototype: HTMLAgoIdentityElement;
        new (): HTMLAgoIdentityElement;
    };
    interface HTMLAgoIframeElement extends Components.AgoIframe, HTMLStencilElement {
    }
    var HTMLAgoIframeElement: {
        prototype: HTMLAgoIframeElement;
        new (): HTMLAgoIframeElement;
    };
    interface HTMLAgoSigninElement extends Components.AgoSignin, HTMLStencilElement {
    }
    var HTMLAgoSigninElement: {
        prototype: HTMLAgoSigninElement;
        new (): HTMLAgoSigninElement;
    };
    interface HTMLAppEmbedElement extends Components.AppEmbed, HTMLStencilElement {
    }
    var HTMLAppEmbedElement: {
        prototype: HTMLAppEmbedElement;
        new (): HTMLAppEmbedElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppPageElement extends Components.AppPage, HTMLStencilElement {
    }
    var HTMLAppPageElement: {
        prototype: HTMLAppPageElement;
        new (): HTMLAppPageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "ago-identity": HTMLAgoIdentityElement;
        "ago-iframe": HTMLAgoIframeElement;
        "ago-signin": HTMLAgoSigninElement;
        "app-embed": HTMLAppEmbedElement;
        "app-home": HTMLAppHomeElement;
        "app-nav": HTMLAppNavElement;
        "app-page": HTMLAppPageElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AgoIdentity {
        "session"?: EmbeddedUserSession;
    }
    interface AgoIframe {
        "iframeUrl"?: string;
        "parentOrigin"?: string;
        "url"?: string;
    }
    interface AgoSignin {
        /**
          * ClientID to identify the app launching OAuth
         */
        "clientid"?: string;
        "displaysignin"?: boolean;
        "displaysignout"?: boolean;
        "onOnSignin"?: (event: CustomEvent<any>) => void;
        "onOnSignout"?: (event: CustomEvent<any>) => void;
        /**
          * url of the ArcGIS Online organization
         */
        "orgurl"?: string;
        /**
          * Serialized authentication information.
         */
        "session"?: EmbeddedUserSession;
        "signin"?: string;
        "signout"?: string;
    }
    interface AppEmbed {
        "embeds"?: string[];
        "match"?: MatchResults;
        "validOrigins"?: string[];
    }
    interface AppHome {
    }
    interface AppNav {
    }
    interface AppPage {
        "history"?: RouterHistory;
        "item"?: any;
        "loading"?: boolean;
        "match"?: MatchResults;
        "messages"?: string[];
        "parentOrigin"?: string;
        "session"?: UserSession;
        "targetItemId"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "ago-identity": AgoIdentity;
        "ago-iframe": AgoIframe;
        "ago-signin": AgoSignin;
        "app-embed": AppEmbed;
        "app-home": AppHome;
        "app-nav": AppNav;
        "app-page": AppPage;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ago-identity": LocalJSX.AgoIdentity & JSXBase.HTMLAttributes<HTMLAgoIdentityElement>;
            "ago-iframe": LocalJSX.AgoIframe & JSXBase.HTMLAttributes<HTMLAgoIframeElement>;
            "ago-signin": LocalJSX.AgoSignin & JSXBase.HTMLAttributes<HTMLAgoSigninElement>;
            "app-embed": LocalJSX.AppEmbed & JSXBase.HTMLAttributes<HTMLAppEmbedElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-page": LocalJSX.AppPage & JSXBase.HTMLAttributes<HTMLAppPageElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
